# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PlantersHandbook' do
  use_frameworks!

  pod 'RealmSwift'
  pod 'UnderLineTextField'
  pod 'SwiftSpinner'
  pod 'JDropDownAlert'
  pod 'EmailValidator'
  pod 'Navajo-Swift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Charts'
  pod 'M13Checkbox'
  pod 'SwiftyGif'

end
